var x = 5;
var y = 15;
var z = 45;
var M = 42;
var string1 = "Ninja";
var string2 = "Dojo";
var string3 = "Web";
var empty = "";
var BooleanT = true;
var BooleanF = false;
console.log("The First Number:", x);
console.log("The Second Number:", y);
console.log("The Third Number:", z);
console.log("The Forth Number:", M);
console.log("The First String:", string1);
console.log("The Second String:", string2);
console.log("The Third String:", string3);
console.log("An Undefined Variable:", empty);
console.log("This statement is True:", BooleanT);
console.log('This statment is "true":', BooleanF);
